### PR TITLE
exception handler for missing .orig file when using /restore switch

### PR DESCRIPTION
**Pull request by ghost**
Goal was functionally the same as before, but matching this new code style.  Just checks for the existence of the backup when /restore is used, and displays an error and English suggestions.

### CODE REVIEW

**Review by janxious — CHANGES_REQUESTED** [review]
Can you get rid of the csproj file changes?

**Comment by ghost** [comment]
I would love to, they crept in on my final commit of course...

**Comment by ghost** [comment]
the only way I know how to do this is by recreating the PR so I'll do that

**Comment by CptMoore** [comment]
Variant A

Mixed reset of branch
Commit again
git push -f 

Variant B

Checkout offending file from untouched branch
Commit that

**Comment by ghost** [comment]
Awesome, thanks for the tips that is a lot easier and cleaner.

**Pull request closed without merging**
